overrides:
  esbuild@<0.28.1: 0.28.2
  qs@<6.15.2: 6.15.2
allowBuilds:
  bufferutil: true
  esbuild: true
minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - vite@8.0.16
  - js-yaml@3.15.0 || 3.15.1
  - body-parser@2.3.0
  - postcss@8.5.18 || 8.5.23
  - nanoid@3.3.16 || 3.3.18
